config: use multiple ips per line
containers/aardvark-dns pull request #183
Opened 2022-07-29 12:58 UTC by Luap99

We have to support several ipv4 and v6 addresses per container. The
current way of creating the configs in aardvark are just broken IMO. We
should never have to duplicate the container id and aliases just to set
more ips.

This patch is fully backwards compatible and will allow much better
config generation in netavark.

2022-07-29 12:58 UTC, Luap99 commented
@flouthoc @mheon PTAL

2022-07-29 15:12 UTC, mheon commented
LGTM

2022-08-01 01:20 UTC, flouthoc requested changes
LGTM, @Luap99 Could you add a section to Readme.md or probably a new `config.md` in this repo, describing the format supported by config. Since as of now we don't have any public format documented. ( Not a blocker )

2022-08-01 08:53 UTC, Luap99 commented
> LGTM, @Luap99 Could you add a section to Readme.md or probably a new `config.md` in this repo, describing the format supported by config. Since as of now we don't have any public format documented. ( Not a blocker )

done

2022-08-01 13:49 UTC, baude commented
/lgtm

2022-08-01 13:52 UTC, merged